### ISSUE TITLE
Project: Thailand's local libraries from OSX's homebrew 

### ISSUE THREAD

**Issue by heytitle** [codeforthailand/org#1]
Homebrew provides a functionality to retrieve formulas from a custom tap. It would be useful if we can develop such a tap and formulas that allow Thai OSX users to conveniently install Thailand-specific libraries. 

For example, those libraries are:
```
- ฟอนต์แห่งชาติ
- dictionary Th-En
```

**Comment by unnawut** [comment]
Sounds really good.

**Comment by heytitle** [comment]
First version is done: https://github.com/codeforthailand/homebrew-siam-ipa.

FYI @unnawut @dtinth

**Comment by unnawut** [comment]
Oh wow! Awesome name! I'm not sure how I can contribute. Please let me know if there're any easy tasks to start with.
